#pragma once


#define MAX_RENDER_TARGET_ATTACHMENTS 8

enum Primitive_Topology
{
	TOPOLOGY_POINT_LIST,
	TOPOLOGY_LINE_LIST,
	TOPOLOGY_LINE_STRIP,
	TOPOLOGY_TRIANGLE_LIST,
	TOPOLOGY_TRIANGLE_STRIP,
	TOPOLOGY_MAX_COUNT
};


enum Usage_Type
{
	USAGE_DEFAULT = 0,
	USAGE_IMMUTABLE = 1,
	USAGE_DYNAMIC = 2,
	USAGE_STAGING = 3
};


enum CPU_Access_Type
{
	ACCESS_NONE = 0,
	ACCESS_WRITE = 1,
	ACCESS_READ = 2,
	ACCESS_WRITE_READ = 3,
};

enum Bind_Flags
{
	BIND_NONE = 1 << 0,
	BIND_VERTEX_BUFFER = 1 << 1,
	BIND_INDEX_BUFFER = 1 << 2,
	BIND_CONSTANT_BUFFER = 1 << 3,
	BIND_SHADER_RESOURCE = 1 << 4,
	BIND_UNORDERED_ACCESS = 1 << 5,
	BIND_RENDER_TARGET = 1 << 6,
	BIND_DEPTH_STENCIL = 1 << 7
};

enum Misc_Flags
{
	MISC_TEXTURE_CUBE = 1 << 0,
	MISC_GENERATE_MIPS = 1 << 1,
	MISC_BUFFER_ALLOW_RAW_VIEWS = 1 << 2,
	MISC_BUFFER_STRUCTURED = 1 << 3,
};


enum Shader_Stages
{
	UNDEFINED_STAGE = 1 << 0,
	VERTEX_STAGE = 1 << 1,
	PIXEL_STAGE = 1 << 2,
	COMPUTE_STAGE = 1 << 3,
};
